image:
  repository: europe-west1-docker.pkg.dev/fc-shared/it-cross/cogvlm-devel
  tag: 0.3.0

config:
  modelRepo: https://huggingface.co/THUDM/cogvlm-chat-hf
  modelLocalDir: /var/models/cogvlm

resources:
  limits:
    nvidia.com/gpu: 1

service:
  type: ClusterIP

name: cogvlm-model

apiGateway:
  enabled: true
  parentRefs:
    name: stable-gateway
    namespace: istio-system

routes:
  cog-ai-model-cog-ai-extra-rule:
    rules:
      - matchesExtra: # Due to implementation constraint only 8 match per rule are allowed
          - path:
              type: PathPrefix
              value: /
            headers:
              - type: Exact           # Exact, RegularExpression
                name: model
                value: cog_change_me  # This is changed by tilt on the fly


# routes.cog-ai-model-cog-ai-extra-rule.rules[0].matchesExtra[0].headers.value="fobarfobar"