image:
  repository: europe-west1-docker.pkg.dev/fc-shared/it-cross/cogvlm-devel
  tag: 0.3.0

config:
  modelRepo: https://huggingface.co/THUDM/cogvlm-chat-hf
  modelLocalDir: /var/models/cogvlm

resources:
  limits:
    nvidia.com/gpu: 1

name: cogvlm-model